# Generated by Django 6.0 on 2025-12-22 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers_payment_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="stripe_payment_intent_id",
            new_name="stripe_session_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
