# Generated by Django 6.0 on 2025-12-23 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
        (
            "users",
            "0005_rename_stripe_payment_intent_id_payment_stripe_session_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="paid_lesson",
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="materials.course",
                verbose_name="Оплаченный курс",
            ),
        ),
    ]
