# Generated by Django 6.0 on 2025-12-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_payment_paid_lesson_alter_payment_paid_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
